version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: 'python app.py'
    ports:
      - 8001:5000
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    volumes:
      - .:/app
    networks:
      - default
      - network1
    external_links:
      - rabbitmq


  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db
    networks:
      - default
      - network1
    external_links:
      - rabbitmq


  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: adv_lnd

    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 33069:5432
    networks:
      - default
      - network1
volumes:
  db:
    driver: local

networks:
  network1:
    external: false
    name: network1