version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default
      - network1
    external_links:
      - rabbitmq

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db
    networks:
      - default
      - network1
    external_links:
      - rabbitmq

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_DB: 'adv_lnd'

    volumes:
      - .dbdata:/var/lib/postgres/data\
    ports:
      - 33068:5432

networks:
  network1:
    external: false
    name: network1